package rewardsonline.accounts;

import static org.junit.Assert.fail;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Scanner;

import javax.sql.DataSource;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

/**
 * SQL query tester. Executes any arbitrary query from a file. The idea is to
 * copy any query generated by Hibernate and run it manually.
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration({ "classpath:datasource/db-config.xml" })
public class QueryTests {

	@Autowired
	private DataSource dataSource;

	/**
	 * Read query from a file.
	 * 
	 * @param file
	 * @return
	 */
	private String readAll(String file) {

		try {
			return new Scanner(new File(file)).useDelimiter("\\Z").next();
		} catch (IOException e) {
			fail();
			return "FAIL"; // Keeps compiler happy. Never reached.
		}
	}

	@Test
	public void testSql() {
		String sql = readAll("query.sql");

		System.out.println("SQL:");
		System.out.println(sql);
		JdbcTemplate t = new JdbcTemplate(dataSource);
		List<Map<String, Object>> results = t.queryForList(sql, "samd");

		System.out.println();
		System.out.println("RESULTS:");

		for (Map<String, Object> row : results) {
			System.out.println("    " + row);
		}
	}
}